[package]
name = "term_clock_pacer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
color-char = "0.2.0"
crossterm = "0.26.1"
termcolor = "1.2.0"
